// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_indexId_ from "./routes/[indexId].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_index_page from "./routes/api/index-page.ts";
import * as $index from "./routes/index.tsx";
import * as $index_all_button from "./islands/index-all-button.tsx";
import * as $index_page_button from "./islands/index-page-button.tsx";
import * as $new_index_button from "./islands/new-index-button.tsx";
import * as $page_details_header from "./islands/page-details-header.tsx";
import * as $page_details from "./islands/page-details.tsx";
import * as $pages_context from "./islands/pages-context.tsx";
import * as $pages_reducer from "./islands/pages-reducer.ts";
import * as $pages from "./islands/pages.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[indexId].tsx": $_indexId_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/index-page.ts": $api_index_page,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/index-all-button.tsx": $index_all_button,
    "./islands/index-page-button.tsx": $index_page_button,
    "./islands/new-index-button.tsx": $new_index_button,
    "./islands/page-details-header.tsx": $page_details_header,
    "./islands/page-details.tsx": $page_details,
    "./islands/pages-context.tsx": $pages_context,
    "./islands/pages-reducer.ts": $pages_reducer,
    "./islands/pages.tsx": $pages,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
