// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_get_index from "./routes/api/get-index.ts";
import * as $api_index_page_pageId_ from "./routes/api/index-page/[pageId].ts";
import * as $api_index_sitemap_database from "./routes/api/index-sitemap-database.ts";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $PageDetails from "./islands/PageDetails.tsx";
import * as $PageDetailsHeader from "./islands/PageDetailsHeader.tsx";
import * as $Pages from "./islands/Pages.tsx";
import * as $PagesContext from "./islands/PagesContext.tsx";
import * as $PagesReducer from "./islands/PagesReducer.ts";
import * as $index_all_button from "./islands/index-all-button.tsx";
import * as $index_page_button from "./islands/index-page-button.tsx";
import * as $new_index_button from "./islands/new-index-button.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/get-index.ts": $api_get_index,
    "./routes/api/index-page/[pageId].ts": $api_index_page_pageId_,
    "./routes/api/index-sitemap-database.ts": $api_index_sitemap_database,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/PageDetails.tsx": $PageDetails,
    "./islands/PageDetailsHeader.tsx": $PageDetailsHeader,
    "./islands/Pages.tsx": $Pages,
    "./islands/PagesContext.tsx": $PagesContext,
    "./islands/PagesReducer.ts": $PagesReducer,
    "./islands/index-all-button.tsx": $index_all_button,
    "./islands/index-page-button.tsx": $index_page_button,
    "./islands/new-index-button.tsx": $new_index_button,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
